### ISSUE TITLE
Harden your GitHub account

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-rvatok#1]
Enable 2FA:
* [x] Proceed at https://github.com/settings/security#two-factor-summary
* [x] I recommend using the following OTP code generator: https://play.google.com/store/apps/details?id=org.liberty.android.freeotpplus&hl=en_US
  * If you've got a Bitwarden subscription or even a FIDO 2 key — it's even better but not mandatory for this task
  * Don't forget to securely store the recovery codes

**Comment by rvatok** [comment]
WIP

**Comment by rvatok** [comment]
Done
