### ISSUE TITLE
Create an empty commit on `main` (and push nothing else there!)

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-rvatok#5]
The following snippet should help you, given that you're starting with a fresh repository that does not have any commits yet.
```console
git commit --allow-empty -m 'Initial commit'
git push origin main
```

Upon the completion of the task, here are the expectations:
1. Only 1 _(one)_ single commit in the `main` branch.
2. The commit is supposed not to add (or remove for that matter) any files at all.
3. There should be 0 _(zero)_ files appearing in the repository at this point.

P.S. It's best to do this task having read the first 3 chapters of the ProGit 2 book from #4.
P.P.S. Fixing an incorrectly created commit would require amending it, or making an interactive rebase. This may imply going through more materials from #4, googling and/or using StackOverflow.

**Comment by webknjaz** [comment]
@rvatok hey, you didn't complete the task correctly. The task was to create an empty commit, but you've added a commit that introduces a README file instead. The correct outcome would be having a single commit on the `main` that does not add anything. Maybe you'll have better understanding when you go through more materials from #4.

**Comment by webknjaz** [comment]
@rvatok try again?

**Comment by rvatok** [comment]
finishing that ticket

**Comment by webknjaz** [comment]
That ticket doesn't give a straight answer, though. You may still need to do some experimentation and googling to get it right. But this should augment the understanding of what you read there.

**Comment by rvatok** [comment]
Done

**Comment by webknjaz** [comment]
Great! I've applied branch protection so any further changes will have to go through branches with PRs.

**Comment by webknjaz** [comment]
@rvatok note that the commit you've made is associated with your second account. You need to adjust the git config to use another email if you want them to be associated with the current account instead. It is possible to do so in single repository settings or globally.
