### ISSUE TITLE
Install NeoVim

### ISSUE THREAD

**Issue by webknjaz** [kpi-web-guild/django-girls-blog-rvatok#8]
* [x] Install NeoVim
* [x] Go through `vimtutor`
* [x] Start using it for writing commit messages
* [x] Optionally, look into integrating https://astronvim.github.io
   * [ ] Try enabling some plugins, like Python syntax highlighting/jedi, flake8
   * [ ] Install RipGrep, fzf

**Comment by rvatok** [comment]
done
